/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
static yyconst short int yy_accept[203] =
    {   0,
        0,    0,   70,   68,   66,   67,   66,    1,   62,   59,
       57,   58,   63,   68,   50,   51,   41,   39,   56,   40,
       68,   42,   11,   11,   43,   54,   45,   44,   46,   60,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   52,   53,   55,   55,   49,
        0,    0,    0,   62,   62,   61,   62,   62,    0,    0,
        0,    0,   16,    0,    0,    0,   12,   13,   48,    0,
        0,   11,   47,   55,   55,   55,   55,   25,   55,   55,
       55,   55,   26,   55,   55,   55,   55,   55,   22,   55,
       55,   31,   55,   55,   55,   55,   55,   55,   55,   55,

       55,   55,    0,   65,   64,   16,   16,    0,    0,   12,
       13,   14,   14,   11,   19,   30,   55,    9,    7,   55,
       38,   37,   55,   55,    6,   28,   34,   55,    5,   32,
       55,    8,    3,   33,   55,   55,   55,   55,   55,   55,
       55,    0,    0,    0,   14,   14,   11,   55,   55,   24,
       55,   36,   55,   55,   35,   23,   15,   55,   55,   55,
       17,   55,    0,    0,    0,   14,   14,   11,   18,   55,
       20,   55,   29,   55,   27,   55,   14,    0,    0,    0,
       11,   55,   21,   55,   55,    0,    0,    0,   11,   55,
       55,   55,    0,   11,   55,    4,   55,    0,   10,   55,

        2,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   38,   39,   38,   40,   41,   42,
       38,   43,   44,   45,   46,   47,   48,   38,   49,   38,
       50,    1,   51,    1,   52,    1,   53,   54,   55,   56,

       38,   38,   57,   38,   38,   38,   38,   38,   58,   38,
       59,   60,   38,   61,   38,   38,   38,   38,   38,   38,
       62,   38,   27,   63,   27,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[64] =
    {   0,
        1,    1,    2,    3,    3,    3,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    4,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3
    } ;

static yyconst short int yy_base[206] =
    {   0,
        0,    0,   99, 1047, 1047, 1047,   58,   59,   62, 1047,
     1047, 1047, 1047,   81,   63,   67,   68,   80,   87,   89,
       88,   46,   90,   96,  105,  106,  109,  112,  113, 1047,
      129,  159,  170,  175,  186,  193,  201,  206,  213,  218,
      225,  238,  233,  246,  251,  114, 1047,  258,  263,  119,
      121,  224,  131,  304,  188, 1047,  294,  299,   45,   59,
      249,  316,  282,  298,  308,  320,  326,  328, 1047,  333,
      338,  345, 1047,  327,  334,  341,  346,  348,  359,  361,
      366,  373,  378,  385,  390,  392,  403,  410,  415,  422,
      429,  417,  436,  443,  448,  460,  455,  462,  474,  476,

      481,  488,  368, 1047, 1047, 1047,  191,  421,  521,  527,
      529,  534,  539,  546,  528,  535,  547,  540,  552,  554,
      559,  566,  571,  573,  578,  585,  590,  592,  597,  605,
      610,  617,  622,  630,  635,  643,  648,  656,  663,  661,
      674,  692,  704,  709,  716,  722,  729,  711,  718,  725,
      733,  738,  740,  752,  757,  759,  770,  772,  788,  786,
      793,  800,  829,  835,  845,  225,  391,  851,  830,  846,
      844,  851,  858,  863,  865,  870,  435,  905,  910,  915,
      922,  904,  911,  918,  916,  517,  758,  947,  957,  936,
      949,  951,  980,  788,  970,  962,  975,  641,  977,  982,

      989, 1047,   64, 1038, 1042
    } ;

static yyconst short int yy_def[206] =
    {   0,
      202,    1,  202,  202,  202,  202,  203,  203,  204,  202,
      202,  202,  202,  205,  203,  203,  203,  203,  203,  203,
      203,  202,  203,  203,  203,  203,  203,  203,  203,  202,
      202,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,  203,  202,   31,   31,  203,
      203,  202,  203,  204,  204,  202,  204,  204,  202,  202,
      203,  202,  203,  203,  203,  203,  203,  203,  202,  203,
      203,  203,  202,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,

       31,   31,  202,  202,  202,  202,  203,  203,  203,  203,
      203,  203,  203,  203,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,  203,  203,  203,  203,  203,  203,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,  203,  203,  203,  203,  203,  203,   31,   31,
       31,   31,   31,   31,   31,   31,  203,  203,  203,  203,
      203,   31,   31,   31,   31,  203,  203,  203,  203,   31,
       31,   31,  203,  203,   31,   31,   31,  203,   31,   31,

       31,    0,  202,  202,  202
    } ;

static yyconst short int yy_nxt[1111] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   21,   30,   31,   32,
       33,   34,   35,   36,   37,   37,   38,   37,   37,   39,
       40,   37,   37,   41,   42,   43,   44,   45,   37,   46,
       47,   21,   37,   48,   37,   49,   37,   37,   37,   37,
       37,   37,   50,   52,   52,   54,   51,   56,   52,  106,
      105,   69,   52,   52,   53,   53,   57,   65,   58,   66,
       59,   60,   60,   53,   53,   52,   62,   60,   60,   60,
       60,   63,   52,   52,   52,   52,   53,   64,  202,   60,

       67,   52,  202,   53,   53,   53,   53,   70,   60,   68,
       52,   52,   53,   71,   52,   72,   72,   52,   52,   52,
      202,   53,   53,  202,   52,   53,   52,   73,   53,   53,
       53,   60,   51,   51,   52,   53,   52,   53,  202,   51,
       51,   51,   51,   51,   51,   53,   51,   53,   74,   74,
       51,   51,   51,   51,   51,   51,  202,   74,   74,   74,
       74,   74,   75,   74,   74,   74,   74,   74,   76,   74,
       74,   77,   78,   74,   74,   74,   74,   74,   51,  202,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   51,   74,   56,  202,  202,   52,  202,   74,   79,

      202,   74,   74,   74,   58,   80,  202,   53,   74,   74,
       81,   82,   74,   74,   74,   83,  202,   74,   74,   74,
       84,   86,  202,  202,   85,   74,   74,  103,   74,   74,
       52,   87,   74,   88,   74,   74,   74,  202,  104,   89,
       74,   53,   59,   74,   74,   90,   74,  202,   74,   74,
      202,   74,   74,   91,   52,   74,   74,   74,   74,  107,
       92,   74,  202,   93,   74,   53,   74,   74,   74,   94,
       95,   74,   98,   96,   99,   74,   74,   74,  202,   74,
       97,   74,  202,  202,   74,   74,  100,   52,   74,   74,
       74,   74,  107,   74,   74,  202,   74,   74,   53,   56,

       74,   74,   74,   52,   56,   74,   74,   54,  107,   56,
       58,  202,  202,   52,   53,   58,  101,  202,   57,  103,
       58,  102,   59,  202,   53,   52,  106,  108,  109,  202,
      104,   52,  202,   52,   59,  202,   53,  202,   52,  108,
      109,  202,   53,   52,   53,  110,  110,  111,  111,   53,
       52,  202,  112,  112,   53,  202,  202,  113,  113,  202,
       74,   53,   71,  202,  114,  114,   74,  115,  202,   74,
       74,  103,  116,   74,   74,  202,   74,   74,  202,   74,
       74,   74,  104,   74,   74,   74,   59,   74,  117,   74,
       74,   74,   74,  202,   74,  202,   52,  118,   74,   74,

       74,   74,   74,  119,   74,  120,  121,   53,   74,   74,
      202,   74,   74,  122,  202,   74,   74,   74,   74,  202,
       74,   74,  202,   74,   74,   74,   52,   74,   74,   74,
      124,   74,   74,  123,   74,   74,   74,   53,  142,  202,
       52,  202,   74,   74,  202,   74,   74,  125,   74,   74,
       74,   53,  126,   74,   74,  127,   74,   74,   74,   74,
       74,   74,   74,  128,   74,   74,  129,  202,   74,   74,
      202,   74,   74,  130,  202,   74,   74,  133,   74,   74,
      131,   74,   74,  202,  202,  132,   74,   74,   74,  134,
       74,   74,  135,   74,   74,   74,  202,   74,   74,   74,

      136,   74,   74,   74,   74,   74,  137,   74,  202,   74,
      202,  202,  139,   74,   74,   74,  138,   74,   74,   74,
       74,   74,   52,   74,   74,  202,   52,   74,  202,  177,
       74,   74,   52,   53,   52,  202,  140,   53,  143,   52,
      144,  144,  141,   53,   52,   53,  110,  110,  111,  111,
       53,   52,  202,  145,  145,   53,  202,  202,  146,  146,
      202,   74,   53,   71,  202,  147,  147,   74,   74,  202,
       74,   74,  202,   74,   74,  148,  202,   74,   74,   74,
       74,  202,   74,   74,  202,   74,   74,   74,  202,   74,
       74,   74,   74,   74,   74,   74,   74,  149,   74,   74,

      202,   74,   74,  150,   74,   74,   74,  202,   74,   74,
       74,   74,   74,   74,   74,   74,  151,   74,   74,  202,
       74,   74,  152,   74,   74,   74,  202,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,  153,   74,   74,
       74,  202,  202,   74,   74,  202,   52,   74,   74,   74,
       74,  154,   74,   74,  202,   74,   74,   53,  143,   74,
       74,   74,  155,   74,   74,   74,  202,  202,   74,   74,
      202,  202,   74,   74,  156,  157,   74,   74,   74,  202,
      202,   74,   74,  202,  158,   74,   74,   74,  202,   74,
       74,   74,  159,  202,   74,   74,   74,   52,   74,   74,

       74,  160,   74,   74,   74,   74,   74,   74,   53,   52,
      202,  163,  163,   74,   52,  202,   74,   74,  202,  202,
       53,   52,  161,  164,  164,   53,  143,   52,  165,  165,
      202,  202,   53,  162,   52,  166,  166,  202,   53,  202,
      202,  167,  167,  202,   74,   53,   71,  202,  168,  168,
       74,   74,  202,   74,   74,  202,  202,   74,   74,  169,
       74,   74,  170,   52,   74,  157,   74,   74,   74,  202,
      177,   74,   74,   74,   53,   74,   74,   74,  202,   74,
       74,   74,   74,   74,  171,   74,  202,  202,  202,  202,
       74,   74,   74,   52,   74,   74,   74,  172,   74,   74,

       74,   74,   74,   74,   53,   74,  202,  194,  194,   74,
      173,   74,   74,   74,   74,   74,  174,  202,  175,   74,
      202,   74,  202,  202,  202,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   52,   74,   74,  202,  202,   74,
       52,  177,   74,   74,  202,   53,  202,  177,  178,  178,
       52,   53,  202,  202,  179,  179,   52,  202,  202,  202,
      176,   53,  143,   74,  180,  180,  202,   53,   71,   74,
      181,  181,   74,   74,  182,  202,  202,   74,  202,   74,
      202,  202,  202,   74,   74,   74,   74,   74,   74,   74,
       74,   74,  184,   74,   74,  183,   74,   74,   74,  202,

       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       52,  202,   74,   74,  202,   52,  202,  177,  202,  202,
       52,   53,  177,  202,  186,  186,   53,   52,  185,  187,
      187,   53,  143,  202,  188,  188,  202,   74,   53,   71,
      202,  189,  189,  190,   74,  202,   74,   74,  202,   74,
       74,   74,   52,   74,   74,   74,  191,   74,   74,   74,
       74,   74,   52,   53,  143,  202,  193,  193,  202,   74,
      202,  202,  192,   53,   71,   74,  194,  194,   74,   74,
      195,  196,   74,  202,   74,   52,  202,  202,   74,  202,
       74,   74,   74,   74,   74,   74,   53,  143,  202,  198,

      198,   74,  199,   74,   74,   74,  202,  202,   74,   74,
       74,  197,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,  202,   74,   74,  202,  200,   74,  202,
      202,   74,   74,  202,  202,  202,  202,  202,  202,  201,
       55,   55,   61,  202,   61,   61,    3,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,

      202,  202,  202,  202,  202,  202,  202,  202,  202,  202
    } ;

static yyconst short int yy_chk[1111] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    7,    8,    9,  203,    9,   15,   60,
       59,   22,   16,   17,    7,    8,    9,   15,    9,   15,
        9,   14,   14,   16,   17,   18,   14,   14,   14,   14,
       14,   14,   19,   21,   20,   23,   18,   14,    3,   14,

       18,   24,    0,   19,   21,   20,   23,   23,   14,   20,
       25,   26,   24,   24,   27,   24,   24,   28,   29,   46,
        0,   25,   26,    0,   50,   27,   51,   27,   28,   29,
       46,   14,   31,   31,   31,   50,   53,   51,    0,   31,
       31,   31,   31,   31,   31,   31,   31,   53,   31,   31,
       31,   31,   31,   31,   31,   31,    0,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,    0,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   32,   55,    0,    0,  107,    0,   32,   32,

        0,   32,   32,   33,   55,   33,   55,  107,   34,   33,
       33,   34,   33,   33,   34,   34,    0,   34,   34,   35,
       35,   36,    0,    0,   35,   35,   36,   52,   35,   35,
      166,   36,   36,   36,   37,   36,   36,    0,   52,   38,
       37,  166,   52,   37,   37,   38,   39,    0,   38,   38,
        0,   40,   39,   39,   61,   39,   39,   40,   41,   61,
       40,   40,    0,   40,   41,   61,   43,   41,   41,   41,
       41,   42,   43,   42,   44,   43,   43,   42,    0,   44,
       42,   42,    0,    0,   45,   44,   45,   63,   44,   44,
       45,   48,   63,   45,   45,    0,   49,   48,   63,   57,

       48,   48,   49,   64,   58,   49,   49,   54,   64,   54,
       57,    0,   57,   65,   64,   58,   48,   58,   54,   62,
       54,   49,   54,    0,   65,   66,   62,   65,   65,    0,
       62,   67,    0,   68,   62,    0,   66,    0,   70,   66,
       66,    0,   67,   71,   68,   67,   67,   68,   68,   70,
       72,    0,   70,   70,   71,    0,    0,   71,   71,    0,
       74,   72,   72,    0,   72,   72,   74,   75,    0,   74,
       74,  103,   76,   75,   76,    0,   75,   75,    0,   77,
       76,   78,  103,   76,   76,   77,  103,   78,   77,   77,
       78,   78,   79,    0,   80,    0,  167,   79,   79,   81,

       80,   79,   79,   80,   80,   81,   82,  167,   81,   81,
        0,   83,   82,   84,    0,   82,   82,   83,   84,    0,
       83,   83,    0,   85,   84,   86,  108,   84,   84,   85,
       86,   86,   85,   85,   86,   86,   87,  108,  108,    0,
      177,    0,   87,   88,    0,   87,   87,   87,   89,   88,
       92,  177,   88,   88,   89,   90,   92,   89,   89,   92,
       92,   90,   91,   90,   90,   90,   90,    0,   91,   93,
        0,   91,   91,   91,    0,   93,   94,   95,   93,   93,
       93,   95,   94,    0,    0,   94,   94,   95,   97,   95,
       95,   95,   96,   96,   97,   98,    0,   97,   97,   96,

       97,   98,   96,   96,   98,   98,   98,   99,    0,  100,
        0,    0,  100,   99,  101,  100,   99,   99,  100,  100,
      101,  102,  186,  101,  101,    0,  109,  102,    0,  186,
      102,  102,  110,  186,  111,    0,  101,  109,  109,  112,
      109,  109,  102,  110,  113,  111,  110,  110,  111,  111,
      112,  114,    0,  112,  112,  113,    0,    0,  113,  113,
        0,  115,  114,  114,    0,  114,  114,  115,  116,    0,
      115,  115,    0,  118,  116,  117,    0,  116,  116,  118,
      117,    0,  118,  118,    0,  119,  117,  120,    0,  117,
      117,  119,  121,  120,  119,  119,  120,  120,  121,  122,

        0,  121,  121,  123,  123,  122,  124,    0,  122,  122,
      123,  125,  124,  123,  123,  124,  124,  125,  126,    0,
      125,  125,  127,  127,  126,  128,    0,  126,  126,  127,
      129,  128,  127,  127,  128,  128,  129,  128,  130,  129,
      129,    0,    0,  131,  130,    0,  198,  130,  130,  131,
      132,  131,  131,  131,    0,  133,  132,  198,  198,  132,
      132,  133,  134,  134,  133,  133,    0,    0,  135,  134,
        0,    0,  134,  134,  135,  136,  136,  135,  135,    0,
        0,  137,  136,    0,  137,  136,  136,  137,    0,  138,
      137,  137,  138,    0,  140,  138,  139,  142,  138,  138,

      140,  139,  139,  140,  140,  139,  139,  141,  142,  143,
        0,  142,  142,  141,  144,    0,  141,  141,    0,    0,
      143,  145,  140,  143,  143,  144,  144,  146,  144,  144,
        0,    0,  145,  141,  147,  145,  145,    0,  146,    0,
        0,  146,  146,    0,  148,  147,  147,    0,  147,  147,
      148,  149,    0,  148,  148,    0,    0,  149,  150,  148,
      149,  149,  149,  187,  150,  151,  151,  150,  150,    0,
      187,  152,  151,  153,  187,  151,  151,  152,    0,  153,
      152,  152,  153,  153,  153,  154,    0,    0,    0,    0,
      155,  154,  156,  194,  154,  154,  155,  154,  156,  155,

      155,  156,  156,  157,  194,  158,    0,  194,  194,  157,
      158,  158,  157,  157,  158,  158,  159,    0,  160,  160,
        0,  159,    0,    0,    0,  160,  161,  159,  160,  160,
      159,  159,  161,  162,  163,  161,  161,    0,    0,  162,
      164,  163,  162,  162,    0,  163,    0,  164,  163,  163,
      165,  164,    0,    0,  164,  164,  168,    0,    0,    0,
      162,  165,  165,  169,  165,  165,    0,  168,  168,  169,
      168,  168,  169,  169,  170,    0,    0,  171,    0,  170,
        0,    0,    0,  171,  172,  170,  171,  171,  170,  170,
      172,  173,  174,  172,  172,  172,  174,  173,  175,    0,

      173,  173,  174,  176,  175,  174,  174,  175,  175,  176,
      178,    0,  176,  176,    0,  179,    0,  178,    0,    0,
      180,  178,  179,    0,  178,  178,  179,  181,  176,  179,
      179,  180,  180,    0,  180,  180,    0,  182,  181,  181,
        0,  181,  181,  182,  183,    0,  182,  182,    0,  185,
      183,  184,  188,  183,  183,  185,  184,  184,  185,  185,
      184,  184,  189,  188,  188,    0,  188,  188,    0,  190,
        0,    0,  185,  189,  189,  190,  189,  189,  190,  190,
      190,  191,  191,    0,  192,  193,    0,    0,  191,    0,
      192,  191,  191,  192,  192,  196,  193,  193,    0,  193,

      193,  196,  195,  195,  196,  196,    0,    0,  197,  195,
      199,  192,  195,  195,  197,  200,  199,  197,  197,  199,
      199,  200,  201,    0,  200,  200,    0,  197,  201,    0,
        0,  201,  201,    0,    0,    0,    0,    0,    0,  200,
      204,  204,  205,    0,  205,  205,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,

      202,  202,  202,  202,  202,  202,  202,  202,  202,  202
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexical.l"
#define INITIAL 0
#line 2 "lexical.l"
	#include <stdio.h>
	#include <stdlib.h>
	#include <string.h>
	#include "TS.h"
	#include "quadruplets.h"
    #include "syntaxique.tab.h"
    extern nb_ligne;
	extern Col;
	char t[100];
    int i=1; 
	int k;
	extern YYSTYPE yylval;
	extern FileName;
	/*
	A REVOIR : 
	-PRBLM INPUT coté droit quand on enleve l'espace une erreur se prod " @"
	-MEME PRBLM les deux cotés output "@"
	*/
#line 696 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 36 "lexical.l"

#line 849 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 203 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1047 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 37 "lexical.l"
{ Col= Col+strlen(yytext); return mc_exl; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 38 "lexical.l"
{ Col= Col+strlen(yytext); return mc_docprogram; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 39 "lexical.l"
{ Col= Col+strlen(yytext); return mc_sub; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 40 "lexical.l"
{ Col= Col+strlen(yytext); return mc_variable; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 41 "lexical.l"
{ Col= Col+strlen(yytext); 
      yylval.string=strdup("INT");
         return mc_int; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 44 "lexical.l"
{  Col= Col+strlen(yytext); yylval.string=strdup("FLT"); return mc_float;} 	
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 45 "lexical.l"
{  Col= Col+strlen(yytext); yylval.string=strdup("CHR");  return mc_char;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 46 "lexical.l"
{  Col= Col+strlen(yytext); yylval.string=strdup("STR"); return mc_string;} 
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 47 "lexical.l"
{  Col= Col+strlen(yytext); yylval.string=strdup("BOL");  return mc_bool;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 48 "lexical.l"
{ Col= Col+strlen(yytext); return mc_constante; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 49 "lexical.l"
{ Col= Col+strlen(yytext); 
   	k=0;
	i=0;
	while(i<strlen(yytext))
	{
		t[k]=yytext[i];
		i++;
		k++;
	}
		if(atoi(t)>32767){
			printf(" erreur sémantique a la ligne %d a la colonne %d de l'entite lexical %s\n",nb_ligne,Col,yytext);
			memset(t, 0, 100);
			return 0;
		}else {
			yylval.entier=atoi(yytext);
			// printf("--------------------------cst plus : %d\n",yylval);
			memset(t, 0, 100);
			return cst_unsigned_int; 
			}
	memset(t, 0, 100);
    return cst_unsigned_int;
	

}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 73 "lexical.l"
{  
	Col= Col+strlen(yytext);
    if(atoi(yytext)>+32767) printf(" erreur semantique a la ligne %d a la colonne %d de l'entite lexical %s\n",nb_ligne,Col,yytext);
	yylval.entier=atoi(yytext);
	return cst_int_pos;
	} 
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 79 "lexical.l"
{  Col= Col+strlen(yytext);
          if( atoi(yytext)<-32768) printf(" erreur semantique a la ligne %d a la colonne %d de l'entite lexical %s\n",nb_ligne,Col,yytext);
 			yylval.entier=atoi(yytext); return cst_int_neg;
} 
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 83 "lexical.l"
{ 
	Col= Col+strlen(yytext); 
		
		
	   if(yytext[0]=='(') {
		   
			k=0;
			i=1;
			while(i<strlen(yytext)-1)
			{
				
				t[k]=yytext[i];
				// printf("%c \t",yytext[i]);
				i++;
				k++;
			}

		//    printf("++++++++++++++++++CST FLT PAR TRUE:%s\n",t);
		yylval.reel=atof(t);
		memset(t, 0, 100);
		i=1;
		k=0;
		   
		}
	   else {
		   
			yylval.reel=atof(yytext);
		//    printf("++++++++++++++++++CST FLT NOT:%s\n",yytext);
		   
		   }
	return cst_float; 
	
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 116 "lexical.l"
{ 
	Col= Col+strlen(yytext); 
	//  if(strcmp(yytext,"TRUE")==0){
	// 	yylval.entier = 1;
	// }else if(strcmp(yytext,"FALSE")==0){
	// 	yylval.entier = 0;
	// }
		yylval.string=strdup(yytext);
	return cst_bool; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 125 "lexical.l"
{ 
	Col= Col+strlen(yytext); 
	yylval.string= strdup(yytext);
	return cst_char; 
	}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 130 "lexical.l"
{ Col= Col+strlen(yytext); return mc_body; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 131 "lexical.l"
{ Col= Col+strlen(yytext); return mc_array; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 132 "lexical.l"
{ Col= Col+strlen(yytext); return mc_aff; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 133 "lexical.l"
{ Col= Col+strlen(yytext); return mc_input; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 134 "lexical.l"
{ Col= Col+strlen(yytext); return mc_output; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 135 "lexical.l"
{ Col= Col+strlen(yytext); return mc_if; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 136 "lexical.l"
{ Col= Col+strlen(yytext); return mc_then; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 137 "lexical.l"
{ Col= Col+strlen(yytext); return mc_else; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 138 "lexical.l"
{ Col= Col+strlen(yytext); return mc_as;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 139 "lexical.l"
{ Col= Col+strlen(yytext); return mc_do;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 140 "lexical.l"
{ Col= Col+strlen(yytext); return mc_while;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 141 "lexical.l"
{ Col= Col+strlen(yytext); return mc_for;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 142 "lexical.l"
{ Col= Col+strlen(yytext); return mc_until;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 143 "lexical.l"
{ Col= Col+strlen(yytext); return and;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 144 "lexical.l"
{ Col= Col+strlen(yytext); return or;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 145 "lexical.l"
{ Col= Col+strlen(yytext); return not;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 146 "lexical.l"
{ Col= Col+strlen(yytext); return sup;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 147 "lexical.l"
{ Col= Col+strlen(yytext); return inf;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 148 "lexical.l"
{ Col= Col+strlen(yytext); return supeg;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 149 "lexical.l"
{ Col= Col+strlen(yytext); return infeg;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 150 "lexical.l"
{ Col= Col+strlen(yytext); return ega;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 151 "lexical.l"
{ Col= Col+strlen(yytext); return dif;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 152 "lexical.l"
{ Col= Col+strlen(yytext); return plus;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 153 "lexical.l"
{ Col= Col+strlen(yytext); return moins;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 154 "lexical.l"
{ Col= Col+strlen(yytext); return mult;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 155 "lexical.l"
{ Col= Col+strlen(yytext); return divis;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 156 "lexical.l"
{ Col= Col+strlen(yytext); return deuxpt; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 157 "lexical.l"
{ Col= Col+strlen(yytext); return egal;} 
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 158 "lexical.l"
{ Col= Col+strlen(yytext); return bal_ouv; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 159 "lexical.l"
{ Col= Col+strlen(yytext); return bal_fer; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 160 "lexical.l"
{ Col= Col+strlen(yytext); return bal_slch_ouv; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 161 "lexical.l"
{ Col= Col+strlen(yytext); return bal_slch_fer; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 162 "lexical.l"
{ Col= Col+strlen(yytext); return ou; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 163 "lexical.l"
{ Col= Col+strlen(yytext); return par_ouv; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 164 "lexical.l"
{ Col= Col+strlen(yytext); return par_fer; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 165 "lexical.l"
{ Col= Col+strlen(yytext); return cr_ouv; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 166 "lexical.l"
{ Col= Col+strlen(yytext); return cr_fer; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 167 "lexical.l"
{ Col= Col+strlen(yytext); return pvg; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 168 "lexical.l"
{ 
	
	Col= Col+strlen(yytext); 
	yylval.string = strdup(yytext);
	return idf; 
	
	}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 175 "lexical.l"
{ Col= Col+strlen(yytext); return vrg; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 176 "lexical.l"
{ Col= Col+strlen(yytext); return dollar; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 177 "lexical.l"
{ Col= Col+strlen(yytext); return mod; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 178 "lexical.l"
{ Col= Col+strlen(yytext); return hash; } 
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 179 "lexical.l"
{ Col= Col+strlen(yytext); return arob; } 
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 180 "lexical.l"
{ 
	Col= Col+strlen(yytext); 
		yylval.string = strdup(yytext);
	return simple_string; 
	}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 185 "lexical.l"
{ 
	Col= Col+strlen(yytext); 
	yylval.string = strdup(yytext);
	return chaine_gauche; 
	}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 190 "lexical.l"
{ Col= Col+strlen(yytext); return etcom; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 191 "lexical.l"
{ 
	Col= Col+strlen(yytext); 
	yylval.string = strdup(yytext);
	return chaine_droite; 
	}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 196 "lexical.l"
{ 
	Col= Col+strlen(yytext); 
	yylval.string = strdup(yytext);
	return chaine_outdr; 
	}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 201 "lexical.l"

	YY_BREAK
case 67:
YY_RULE_SETUP
#line 202 "lexical.l"
{Col= 1; nb_ligne++;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 203 "lexical.l"
{ 
	
	printf("File \"%s\", line %d, character %d:lexical error\n",FileName,nb_ligne,Col);
	//yyerror("lexical error a la ligne %d colonne %d sur l'entite %s \n",nb_ligne,Col,yytext);
	}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 208 "lexical.l"
ECHO;
	YY_BREAK
#line 1380 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 203 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 203 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 202);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 208 "lexical.l"
